import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { cn } from '~/lib/utils'
import { neueMachina } from '~/fonts'

const fig = Figtree({
  variable: '--font-fig',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('antialiased', fig.variable, neueMachina.variable)}>
        {children}
      </body>
    </html>
  )
}
